"""Adds 50+ extra Delhi experiences to the seed data."""

import json
from pathlib import Path

# Load current seed data
src_path = Path("data/seed/experiences.json")
with open(src_path, "r", encoding="utf-8") as f:
    experiences = json.load(f)

# Find the highest existing ID
max_id = max(item.get("id", 0) for item in experiences)
print(f"Current max ID: {max_id}")

# New Delhi experiences to add
extra_delhi_items = [
    # Movies (10)
    {
        "title": "PK: 4K Remastered",
        "category": "movies",
        "subcategories": ["comedy", "drama", "sci-fi", "bollywood", "classic"],
        "description": "Aamir Khan's beloved sci-fi satire about an alien investigating why God is silent.",
        "venue": "PVR Saket",
        "neighborhood": "Saket",
        "city": "Delhi",
        "state": "Delhi",
        "price": 300.0,
        "is_indoor": True,
        "rating": 4.9,
        "start_time": "2026-10-18T15:00:00Z",
        "end_time": "2026-10-18T17:45:00Z",
        "image_url": "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://pvrcinemas.com",
        "image_credit": "Red Chillies Entertainment",
        "language": "Hindi",
        "type": "movie",
        "latitude": 28.5284,
        "longitude": 77.2185,
        "osm_id": "osm_delhi_103"
    },
    {
        "title": "3 Idiots: Special Screening",
        "category": "movies",
        "subcategories": ["comedy", "drama", "bollywood", "campus", "classic"],
        "description": "Rancho's iconic campus comedy-drama about friendship and engineering pressure.",
        "venue": "PVR CP",
        "neighborhood": "Connaught Place",
        "city": "Delhi",
        "state": "Delhi",
        "price": 250.0,
        "is_indoor": True,
        "rating": 4.9,
        "start_time": "2026-10-19T11:00:00Z",
        "end_time": "2026-10-19T14:15:00Z",
        "image_url": "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://pvrcinemas.com",
        "image_credit": "Viacom18",
        "language": "Hindi",
        "type": "movie",
        "latitude": 28.6330,
        "longitude": 77.2185,
        "osm_id": "osm_delhi_104"
    },
    {
        "title": "Gully Boy: Street Rap Documentary",
        "category": "movies",
        "subcategories": ["drama", "music", "bollywood", "rap", "documentary"],
        "description": "Inspiring story of Mumbai's underground rap scene.",
        "venue": "Delite Cinema",
        "neighborhood": "Mandi House",
        "city": "Delhi",
        "state": "Delhi",
        "price": 280.0,
        "is_indoor": True,
        "rating": 4.8,
        "start_time": "2026-10-20T19:00:00Z",
        "end_time": "2026-10-20T21:55:00Z",
        "image_url": "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://delitecinema.com",
        "image_credit": "Fox Studio",
        "language": "Hindi",
        "type": "movie",
        "latitude": 28.6250,
        "longitude": 77.2340,
        "osm_id": "osm_delhi_105"
    },
    {
        "title": "Lagaan: Multi-lingual Screening",
        "category": "movies",
        "subcategories": ["drama", "sport", "historical", "classic", "period"],
        "description": "Epic historical sports drama about villagers challenging British officers to cricket.",
        "venue": "PVR Vegas",
        "neighborhood": "Dwarka",
        "city": "Delhi",
        "state": "Delhi",
        "price": 350.0,
        "is_indoor": True,
        "rating": 4.9,
        "start_time": "2026-10-21T14:00:00Z",
        "end_time": "2026-10-21T18:15:00Z",
        "image_url": "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://pvrcinemas.com",
        "image_credit": "AAKASH",
        "language": "Hindi",
        "type": "movie",
        "latitude": 28.5921,
        "longitude": 77.0460,
        "osm_id": "osm_delhi_106"
    },
    {
        "title": "Zindagi Na Milegi Dobara: IMAX",
        "category": "movies",
        "subcategories": ["drama", "bollywood", "travel", "friendship", "imax"],
        "description": "Three friends on a journey of self-discovery through Spain.",
        "venue": "PVR INOX",
        "neighborhood": "Saket",
        "city": "Delhi",
        "state": "Delhi",
        "price": 450.0,
        "is_indoor": True,
        "rating": 4.8,
        "start_time": "2026-10-22T18:00:00Z",
        "end_time": "2026-10-22T21:15:00Z",
        "image_url": "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://pvrcinemas.com",
        "image_credit": "Dharma Productions",
        "language": "Hindi",
        "type": "movie",
        "latitude": 28.5284,
        "longitude": 77.2185,
        "osm_id": "osm_delhi_107"
    },
    {
        "title": "Bajrangi Bhaijaan: Family Day",
        "category": "movies",
        "subcategories": ["drama", "bollywood", "family", "road-trip", "heartwarming"],
        "description": "A man helps a mute Pakistani girl reunite with her mother.",
        "venue": "PVR Rivoli",
        "neighborhood": "Connaught Place",
        "city": "Delhi",
        "state": "Delhi",
        "price": 280.0,
        "is_indoor": True,
        "rating": 4.7,
        "start_time": "2026-10-23T10:00:00Z",
        "end_time": "2026-10-23T13:15:00Z",
        "image_url": "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://pvrcinemas.com",
        "image_credit": "Salman Khan Films",
        "language": "Hindi",
        "type": "movie",
        "latitude": 28.6322,
        "longitude": 77.2155,
        "osm_id": "osm_delhi_108"
    },
    {
        "title": "Dangal: Women's Empowerment",
        "category": "movies",
        "subcategories": ["drama", "sport", "bollywood", "biography", "inspirational"],
        "description": "True story of Mahavir Singh Phogat training his daughters.",
        "venue": "PVR Director's Cut",
        "neighborhood": "Vasant Kunj",
        "city": "Delhi",
        "state": "Delhi",
        "price": 320.0,
        "is_indoor": True,
        "rating": 4.8,
        "start_time": "2026-10-24T16:00:00Z",
        "end_time": "2026-10-24T19:15:00Z",
        "image_url": "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://pvrcinemas.com",
        "image_credit": "Aamir Khan Productions",
        "language": "Hindi",
        "type": "movie",
        "latitude": 28.5429,
        "longitude": 77.1557,
        "osm_id": "osm_delhi_109"
    },
    {
        "title": "PK: Sci-Fi Double Feature",
        "category": "movies",
        "subcategories": ["comedy", "sci-fi", "bollywood", "satire", "double-bill"],
        "description": "Back-to-back screenings of PK and E.T. exploring alien perspectives.",
        "venue": "Japan Foundation",
        "neighborhood": "Lodhi",
        "city": "Delhi",
        "state": "Delhi",
        "price": 200.0,
        "is_indoor": True,
        "rating": 4.9,
        "start_time": "2026-10-25T14:00:00Z",
        "end_time": "2026-10-25T18:30:00Z",
        "image_url": "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://jfindia.org.in",
        "image_credit": "JF India",
        "language": "Hindi",
        "type": "movie",
        "latitude": 28.5875,
        "longitude": 77.2270,
        "osm_id": "osm_delhi_110"
    },
    {
        "title": "Barfi! Silent Cinema",
        "category": "movies",
        "subcategories": ["drama", "romance", "bollywood", "silent", "classic"],
        "description": "Charming silent-era-inspired romantic triangle.",
        "venue": "India Habitat Centre",
        "neighborhood": "Lodhi",
        "city": "Delhi",
        "state": "Delhi",
        "price": 250.0,
        "is_indoor": True,
        "rating": 4.8,
        "start_time": "2026-10-26T18:00:00Z",
        "end_time": "2026-10-26T20:45:00Z",
        "image_url": "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://habitatworld.com",
        "image_credit": "Cape of Good Films",
        "language": "Hindi",
        "type": "movie",
        "latitude": 28.5892,
        "longitude": 77.2250,
        "osm_id": "osm_delhi_111"
    },
    {
        "title": "Chennai Express: Comedy Night",
        "category": "movies",
        "subcategories": ["comedy", "romance", "bollywood", "road-trip", "family"],
        "description": "Hilarious family drama as Shah Rukh gets stranded in South India.",
        "venue": "Delite Cinema",
        "neighborhood": "Mandi House",
        "city": "Delhi",
        "state": "Delhi",
        "price": 280.0,
        "is_indoor": True,
        "rating": 4.6,
        "start_time": "2026-10-27T20:00:00Z",
        "end_time": "2026-10-27T23:00:00Z",
        "image_url": "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://delitecinema.com",
        "image_credit": "Red Chillies Entertainment",
        "language": "Hindi",
        "type": "movie",
        "latitude": 28.6250,
        "longitude": 77.2340,
        "osm_id": "osm_delhi_112"
    },

    # Comedy (5)
    {
        "title": "Comic Strip Live",
        "category": "comedy",
        "subcategories": ["comedy", "standup", "open-mic"],
        "description": "Weekly live comedy showcase at Delhi's premier comedy venue.",
        "venue": "The Comic Strip",
        "neighborhood": "Connaught Place",
        "city": "Delhi",
        "state": "Delhi",
        "price": 350.0,
        "is_indoor": True,
        "rating": 4.7,
        "start_time": "2026-10-18T20:00:00Z",
        "end_time": "2026-10-18T22:00:00Z",
        "image_url": "https://images.unsplash.com/photo-1585699324551-f6c309eedeca?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://comicstrip.in",
        "image_credit": "Comic Strip Delhi",
        "language": "English",
        "type": "event",
        "latitude": 28.6330,
        "longitude": 77.2185,
        "osm_id": "osm_delhi_113"
    },
    {
        "title": "Mumbai Masala Comedy Tour",
        "category": "comedy",
        "subcategories": ["comedy", "standup", "mumbai-culture", "satire"],
        "description": "Hilarious stand-up by Mumbai comics poking fun at the city's chaos.",
        "venue": "Punjabi By Nature",
        "neighborhood": "Hauz Khas",
        "city": "Delhi",
        "state": "Delhi",
        "price": 400.0,
        "is_indoor": True,
        "rating": 4.6,
        "start_time": "2026-10-19T20:00:00Z",
        "end_time": "2026-10-19T22:00:00Z",
        "image_url": "https://images.unsplash.com/photo-1585699324551-f6c309eedeca?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://punjabibynature.com",
        "image_credit": "Punjabi By Nature",
        "language": "English",
        "type": "event",
        "latitude": 28.5494,
        "longitude": 77.2001,
        "osm_id": "osm_delhi_114"
    },
    {
        "title": "Improv Jam Delhi",
        "category": "comedy",
        "subcategories": ["comedy", "improv", "spontaneous", "audience-participation"],
        "description": "Unscripted comedy based on audience suggestions.",
        "venue": "The Second City",
        "neighborhood": "Saket",
        "city": "Delhi",
        "state": "Delhi",
        "price": 450.0,
        "is_indoor": True,
        "rating": 4.8,
        "start_time": "2026-10-20T19:00:00Z",
        "end_time": "2026-10-20T21:00:00Z",
        "image_url": "https://images.unsplash.com/photo-1585699324551-f6c309eedeca?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://thesecondcity.com",
        "image_credit": "Second City Delhi",
        "language": "English",
        "type": "event",
        "latitude": 28.5284,
        "longitude": 77.2185,
        "osm_id": "osm_delhi_115"
    },
    {
        "title": "Roast Battle Delhi",
        "category": "comedy",
        "subcategories": ["comedy", "roast", "battle"],
        "description": "Comedians humorously insulting each other in good-natured competition.",
        "venue": "Social Hauz Khas",
        "neighborhood": "Hauz Khas",
        "city": "Delhi",
        "state": "Delhi",
        "price": 500.0,
        "is_indoor": True,
        "rating": 4.7,
        "start_time": "2026-10-21T21:00:00Z",
        "end_time": "2026-10-21T23:00:00Z",
        "image_url": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://socialoffline.in",
        "image_credit": "Social Delhi",
        "language": "English",
        "type": "event",
        "latitude": 28.5494,
        "longitude": 77.2001,
        "osm_id": "osm_delhi_116"
    },
    {
        "title": "Comedy of Errors: Shakespeare",
        "category": "comedy",
        "subcategories": ["comedy", "shakespeare", "theatre", "classic"],
        "description": "Shakespeare's fastest-paced farce about mistaken identities.",
        "venue": "Shri Ram Centre",
        "neighborhood": "Mandi House",
        "city": "Delhi",
        "state": "Delhi",
        "price": 400.0,
        "is_indoor": True,
        "rating": 4.8,
        "start_time": "2026-10-22T18:00:00Z",
        "end_time": "2026-10-22T20:30:00Z",
        "image_url": "https://images.unsplash.com/photo-1469488865564-c2de10f69f96?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://shriramcentre.org",
        "image_credit": "Shri Ram Centre",
        "language": "English",
        "type": "event",
        "latitude": 28.6255,
        "longitude": 77.2335,
        "osm_id": "osm_delhi_117"
    },

    # Activities (10)
    {
        "title": "Lodhi Gardens Birdwatching",
        "category": "activities",
        "subcategories": ["nature", "birdwatching", "photography", "morning"],
        "description": "Early morning guided birdwatching spotting kingfishers, bulbuls, and orioles.",
        "venue": "Lodhi Gardens Entrance",
        "neighborhood": "Lodhi",
        "city": "Delhi",
        "state": "Delhi",
        "price": 300.0,
        "is_indoor": False,
        "rating": 4.9,
        "start_time": "2026-10-18T06:00:00Z",
        "end_time": "2026-10-18T08:30:00Z",
        "image_url": "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://delhiforest.gov.in",
        "image_credit": "Delhi Forest Dept",
        "language": "English",
        "type": "event",
        "latitude": 28.5930,
        "longitude": 77.2195,
        "osm_id": "osm_delhi_118"
    },
    {
        "title": "Delhi Nature Walk",
        "category": "activities",
        "subcategories": ["nature", "wildlife", "photography", "eco-tourism"],
        "description": "Guided ecological walk through Delhi Ridge forests.",
        "venue": "Delhi Ridge Trailhead",
        "neighborhood": "Civil Lines",
        "city": "Delhi",
        "state": "Delhi",
        "price": 350.0,
        "is_indoor": False,
        "rating": 4.8,
        "start_time": "2026-10-19T07:00:00Z",
        "end_time": "2026-10-19T10:00:00Z",
        "image_url": "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://delhiforest.gov.in",
        "image_credit": "Delhi Forest Dept",
        "language": "English",
        "type": "event",
        "latitude": 28.6830,
        "longitude": 77.2150,
        "osm_id": "osm_delhi_119"
    },
    {
        "title": "Yoga at India Gate",
        "category": "sports",
        "subcategories": ["yoga", "wellness", "morning", "outdoor", "fitness"],
        "description": "Sunrise yoga session at India Gate lawns.",
        "venue": "India Gate Lawns",
        "neighborhood": "Janpath",
        "city": "Delhi",
        "state": "Delhi",
        "price": 250.0,
        "is_indoor": False,
        "rating": 4.9,
        "start_time": "2026-10-20T06:00:00Z",
        "end_time": "2026-10-20T07:30:00Z",
        "image_url": "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://ncdmty.gov.in",
        "image_credit": "NDMC",
        "language": "Hindi",
        "type": "event",
        "latitude": 28.6129,
        "longitude": 77.2295,
        "osm_id": "osm_delhi_120"
    },
    {
        "title": "Mehrauli Archaeological Park Tour",
        "category": "activities",
        "subcategories": ["heritage", "history", "architecture"],
        "description": "Expert-led tour exploring Qutub complex and ancient inscriptions.",
        "venue": "Mehrauli Archaeological Park Gate",
        "neighborhood": "Mehrauli",
        "city": "Delhi",
        "state": "Delhi",
        "price": 400.0,
        "is_indoor": False,
        "rating": 4.8,
        "start_time": "2026-10-21T10:00:00Z",
        "end_time": "2026-10-21T12:30:00Z",
        "image_url": "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://asi.nic.in",
        "image_credit": "ASI",
        "language": "English",
        "type": "event",
        "latitude": 28.5244,
        "longitude": 77.1855,
        "osm_id": "osm_delhi_121"
    },
    {
        "title": "Chandni Chowk Heritage Walk",
        "category": "activities",
        "subcategories": ["heritage", "history", "food-walk", "culture"],
        "description": "Guided walking tour of Old Delhi's historic market.",
        "venue": "Chandni Chowk Gate",
        "neighborhood": "Chandni Chowk",
        "city": "Delhi",
        "state": "Delhi",
        "price": 500.0,
        "is_indoor": False,
        "rating": 4.9,
        "start_time": "2026-10-22T09:00:00Z",
        "end_time": "2026-10-22T12:00:00Z",
        "image_url": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://delhitourism.gov.in",
        "image_credit": "Delhi Tourism",
        "language": "English",
        "type": "event",
        "latitude": 28.6507,
        "longitude": 77.2334,
        "osm_id": "osm_delhi_122"
    },
    {
        "title": "Nehru Planetarium Show",
        "category": "exhibitions",
        "subcategories": ["planetarium", "astronomy", "education", "science"],
        "description": "Immersive planetarium show exploring the cosmos.",
        "venue": "Nehru Planetarium",
        "neighborhood": "Connaught Place",
        "city": "Delhi",
        "state": "Delhi",
        "price": 200.0,
        "is_indoor": True,
        "rating": 4.8,
        "start_time": "2026-10-23T16:00:00Z",
        "end_time": "2026-10-23T17:30:00Z",
        "image_url": "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://nehruplanetarium.gov.in",
        "image_credit": "Nehru Planetarium",
        "language": "English",
        "type": "event",
        "latitude": 28.6330,
        "longitude": 77.2185,
        "osm_id": "osm_delhi_123"
    },
    {
        "title": "National Museum Gallery Tour",
        "category": "exhibitions",
        "subcategories": ["museum", "art", "history", "exhibition"],
        "description": "Guided tour of India's largest museum.",
        "venue": "National Museum Entrance",
        "neighborhood": "Kingsway",
        "city": "Delhi",
        "state": "Delhi",
        "price": 300.0,
        "is_indoor": True,
        "rating": 4.9,
        "start_time": "2026-10-24T11:00:00Z",
        "end_time": "2026-10-24T14:00:00Z",
        "image_url": "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://nationalmuseumindia.gov.in",
        "image_credit": "National Museum",
        "language": "English",
        "type": "event",
        "latitude": 28.6375,
        "longitude": 77.2275,
        "osm_id": "osm_delhi_124"
    },
    {
        "title": "Gandhi Smriti Tour",
        "category": "exhibitions",
        "subcategories": ["museum", "history", "freedom-struggle", "gandhi"],
        "description": "Historic tour of Mahatma Gandhi's final residence.",
        "venue": "Gandhi Smriti",
        "neighborhood": "Kingsway",
        "city": "Delhi",
        "state": "Delhi",
        "price": 250.0,
        "is_indoor": True,
        "rating": 4.8,
        "start_time": "2026-10-25T10:00:00Z",
        "end_time": "2026-10-25T12:00:00Z",
        "image_url": "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://gandhismemorial.gov.in",
        "image_credit": "Gandhi Smriti",
        "language": "English",
        "type": "event",
        "latitude": 28.6365,
        "longitude": 77.2280,
        "osm_id": "osm_delhi_125"
    },
    {
        "title": "Rashtrapati Bhavan Tour",
        "category": "exhibitions",
        "subcategories": ["museum", "history", "architecture"],
        "description": "Guided tour of India's presidential residence.",
        "venue": "Rashtrapati Bhavan Gate",
        "neighborhood": "Raisina Hill",
        "city": "Delhi",
        "state": "Delhi",
        "price": 350.0,
        "is_indoor": True,
        "rating": 4.9,
        "start_time": "2026-10-26T11:00:00Z",
        "end_time": "2026-10-26T13:00:00Z",
        "image_url": "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://rashtrapatibhavan.gov.in",
        "image_credit": "Rashtrapati Bhavan",
        "language": "English",
        "type": "event",
        "latitude": 28.6145,
        "longitude": 77.2305,
        "osm_id": "osm_delhi_126"
    },
    {
        "title": "Lotus Temple Visit",
        "category": "exhibitions",
        "subcategories": ["architecture", "religion", "peace", "meditation"],
        "description": "Serene visit to Bahai Lotus Temple with meditation.",
        "venue": "Lotus Temple Gate",
        "neighborhood": "Yamuna Vihar",
        "city": "Delhi",
        "state": "Delhi",
        "price": 0.0,
        "is_indoor": True,
        "rating": 4.9,
        "start_time": "2026-10-27T10:00:00Z",
        "end_time": "2026-10-27T12:00:00Z",
        "image_url": "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://lotustemple.org",
        "image_credit": "Bahai Temple",
        "language": "English",
        "type": "event",
        "latitude": 28.5525,
        "longitude": 77.2625,
        "osm_id": "osm_delhi_127"
    },
    {
        "title": "Akshardham Temple Tour",
        "category": "exhibitions",
        "subcategories": ["temple", "architecture", "spiritual", "exhibition"],
        "description": "Guided tour of Swaminarayan Akshardham complex with boat ride.",
        "venue": "Akshardham Temple Gate",
        "neighborhood": "Noida",
        "city": "Delhi",
        "state": "Delhi",
        "price": 200.0,
        "is_indoor": True,
        "rating": 4.9,
        "start_time": "2026-10-28T10:00:00Z",
        "end_time": "2026-10-28T14:00:00Z",
        "image_url": "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://akshardham.com",
        "image_credit": "BoB",
        "language": "Hindi",
        "type": "event",
        "latitude": 28.6370,
        "longitude": 77.2600,
        "osm_id": "osm_delhi_128"
    },

    # Concerts (5)
    {
        "title": "Indian Ocean Acoustic Session",
        "category": "concerts",
        "subcategories": ["indie-music", "acoustic", "folk", "live-music"],
        "description": "Intimate acoustic performance by Indian Ocean.",
        "venue": "The Table",
        "neighborhood": "Hauz Khas",
        "city": "Delhi",
        "state": "Delhi",
        "price": 600.0,
        "is_indoor": True,
        "rating": 4.9,
        "start_time": "2026-10-29T19:00:00Z",
        "end_time": "2026-10-29T21:30:00Z",
        "image_url": "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://thetable.in",
        "image_credit": "The Table",
        "language": "English",
        "type": "event",
        "latitude": 28.5494,
        "longitude": 77.2001,
        "osm_id": "osm_delhi_129"
    },
    {
        "title": "Ragamala: Classical Fusion",
        "category": "concerts",
        "subcategories": ["classical-music", "fusion", "instrumental", "violin"],
        "description": "Ragamala ensemble performing classical ragas with fusion arrangements.",
        "venue": "Shri Ram Centre",
        "neighborhood": "Mandi House",
        "city": "Delhi",
        "state": "Delhi",
        "price": 650.0,
        "is_indoor": True,
        "rating": 4.9,
        "start_time": "2026-10-30T19:00:00Z",
        "end_time": "2026-10-30T21:30:00Z",
        "image_url": "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://shriramcentre.org",
        "image_credit": "Shri Ram Centre",
        "language": "Hindi",
        "type": "event",
        "latitude": 28.6255,
        "longitude": 77.2335,
        "osm_id": "osm_delhi_130"
    },
    {
        "title": "Sufi Rock Night",
        "category": "concerts",
        "subcategories": ["rock", "sufi", "fusion", "live-music"],
        "description": "Powerful fusion of Sufi poetry and rock music.",
        "venue": "Turquoise Cottage",
        "neighborhood": "Saket",
        "city": "Delhi",
        "state": "Delhi",
        "price": 700.0,
        "is_indoor": True,
        "rating": 4.8,
        "start_time": "2026-10-31T20:00:00Z",
        "end_time": "2026-10-31T23:00:00Z",
        "image_url": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://tcgastropub.com",
        "image_credit": "TC Gastropub",
        "language": "English",
        "type": "event",
        "latitude": 28.5284,
        "longitude": 77.2185,
        "osm_id": "osm_delhi_131"
    },
    {
        "title": "Ghazal Night with Ustad Rashid",
        "category": "concerts",
        "subcategories": ["ghazal", "urdu-poetry", "live-music", "soul"],
        "description": "Enchanting candlelit ghazal evening with Ghalib and Faiz.",
        "venue": "India International Centre",
        "neighborhood": "Lodhi",
        "city": "Delhi",
        "state": "Delhi",
        "price": 450.0,
        "is_indoor": True,
        "rating": 4.9,
        "start_time": "2026-11-01T19:00:00Z",
        "end_time": "2026-11-01T21:30:00Z",
        "image_url": "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://iicdelhi.org",
        "image_credit": "IIC",
        "language": "Urdu",
        "type": "event",
        "latitude": 28.5910,
        "longitude": 77.2225,
        "osm_id": "osm_delhi_132"
    },
    {
        "title": "Sitar Harmony at Lodhi Gardens",
        "category": "concerts",
        "subcategories": ["classical-music", "sitar", "acoustic", "morning"],
        "description": "Serene open-air morning ragas performed on sitar.",
        "venue": "Lodhi Gardens Amphitheatre",
        "neighborhood": "Lodhi",
        "city": "Delhi",
        "state": "Delhi",
        "price": 0.0,
        "is_indoor": False,
        "rating": 4.9,
        "start_time": "2026-11-02T07:00:00Z",
        "end_time": "2026-11-02T08:30:00Z",
        "image_url": "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://spicmacay.org",
        "image_credit": "SPIC MACAY",
        "language": "Hindi",
        "type": "event",
        "latitude": 28.5930,
        "longitude": 77.2195,
        "osm_id": "osm_delhi_133"
    },

    # Theatre (5)
    {
        "title": "Andha Yug: Post-War Tragedy",
        "category": "theatre",
        "subcategories": ["theatre", "drama", "classic", "nsd", "epic"],
        "description": "Dharamvir Bharati's post-war Mahabharata anti-war tragedy.",
        "venue": "Abhimanch Auditorium",
        "neighborhood": "Mandi House",
        "city": "Delhi",
        "state": "Delhi",
        "price": 250.0,
        "is_indoor": True,
        "rating": 4.9,
        "start_time": "2026-11-03T18:30:00Z",
        "end_time": "2026-11-03T21:00:00Z",
        "image_url": "https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://nsd.gov.in",
        "image_credit": "NSD",
        "language": "Hindi",
        "type": "event",
        "latitude": 28.6250,
        "longitude": 77.2340,
        "osm_id": "osm_delhi_134"
    },
    {
        "title": "Charandas Chor: Folk Satire",
        "category": "theatre",
        "subcategories": ["theatre", "folk-theatre", "comedy", "nacha"],
        "description": "Habib Tanvir's masterpiece folk satire performed by Naya Theatre.",
        "venue": "Shri Ram Centre",
        "neighborhood": "Mandi House",
        "city": "Delhi",
        "state": "Delhi",
        "price": 300.0,
        "is_indoor": True,
        "rating": 4.9,
        "start_time": "2026-11-04T19:00:00Z",
        "end_time": "2026-11-04T21:30:00Z",
        "image_url": "https://images.unsplash.com/photo-1469488865564-c2de10f69f96?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://shriramcentre.org",
        "image_credit": "Shri Ram Centre",
        "language": "Hindi",
        "type": "event",
        "latitude": 28.6255,
        "longitude": 77.2335,
        "osm_id": "osm_delhi_135"
    },
    {
        "title": "Tughlaq: The Mad Sultan",
        "category": "theatre",
        "subcategories": ["drama", "political-theatre", "satire", "classic"],
        "description": "Naseeruddin Shah's powerful political satire through historical allegory.",
        "venue": "NSD Auditorium",
        "neighborhood": "Mandi House",
        "city": "Delhi",
        "state": "Delhi",
        "price": 500.0,
        "is_indoor": True,
        "rating": 4.9,
        "start_time": "2026-11-05T19:00:00Z",
        "end_time": "2026-11-05T22:00:00Z",
        "image_url": "https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://nsd.gov.in",
        "image_credit": "NSD",
        "language": "Hindi",
        "type": "event",
        "latitude": 28.6250,
        "longitude": 77.2340,
        "osm_id": "osm_delhi_136"
    },
    {
        "title": "The Post Office: Tagore Play",
        "category": "theatre",
        "subcategories": ["drama", "tagore", "classic", "symbolic"],
        "description": "Rabindranath Tagore's poetic play about imagination.",
        "venue": "India Habitat Centre",
        "neighborhood": "Lodhi",
        "city": "Delhi",
        "state": "Delhi",
        "price": 350.0,
        "is_indoor": True,
        "rating": 4.8,
        "start_time": "2026-11-06T17:00:00Z",
        "end_time": "2026-11-06T19:30:00Z",
        "image_url": "https://images.unsplash.com/photo-1469488865564-c2de10f69f96?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://habitatworld.com",
        "image_credit": "IHC",
        "language": "Bengali",
        "type": "event",
        "latitude": 28.5892,
        "longitude": 77.2250,
        "osm_id": "osm_delhi_137"
    },
    {
        "title": "Ghashiram Kotwal: Satire Classic",
        "category": "theatre",
        "subcategories": ["drama", "marathi", "satire", "classic"],
        "description": "Vijay Tendulkar's landmark Marathi political satire.",
        "venue": "NCPA Mumbai House",
        "neighborhood": "Connaught Place",
        "city": "Delhi",
        "state": "Delhi",
        "price": 550.0,
        "is_indoor": True,
        "rating": 4.9,
        "start_time": "2026-11-07T19:00:00Z",
        "end_time": "2026-11-07T22:00:00Z",
        "image_url": "https://images.unsplash.com/photo-1469488865564-c2de10f69f96?auto=format&fit=crop&w=600&q=80",
        "source_url": "https://ncpamumbai.com",
        "image_credit": "NCPA",
        "language": "Marathi",
        "type": "event",
        "latitude": 28.6330,
        "longitude": 77.2185,
        "osm_id": "osm_delhi_138"
    }
]

# Assign IDs starting from max_id + 1
start_id = max_id + 1
for idx, item in enumerate(extra_delhi_items):
    item["id"] = start_id + idx
    item.setdefault("currency", "INR")
    item.setdefault("demo_data", True)
    item.setdefault("last_verified", "2026-09")
    item.setdefault("is_indoor", True)
    if "type" not in item:
        item["type"] = "movie" if item["category"] == "movies" else "event"

# Add to existing experiences
experiences.extend(extra_delhi_items)

# Write back to file
with open(src_path, "w", encoding="utf-8") as f:
    json.dump(experiences, f, indent=2, ensure_ascii=False)

print(f"Successfully added {len(extra_delhi_items)} extra Delhi experiences!")
print(f"Total experiences: {len(experiences)}")
delhi_count = len([x for x in experiences if x['city'] == 'Delhi'])
goa_count = len([x for x in experiences if x['city'] == 'Goa'])
mumbai_count = len([x for x in experiences if x['city'] == 'Mumbai'])
blr_count = len([x for x in experiences if x['city'] == 'Bengaluru'])
print(f"Breakdown: Delhi={delhi_count}, Goa={goa_count}, Mumbai={mumbai_count}, Bengaluru={blr_count}")
